use_frameworks!

platform :ios, '10.0'

target 'CombineNetworking_Example' do
  pod 'CombineNetworking', :path => '../'

  target 'CombineNetworking_Tests' do
    inherit! :search_paths

    
  end
end
